// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Tf4QFd5ZOgZ_6kxqsA888gxyuCK3ch8',
    appId: '1:168191455701:web:ce5d8653a22cdf0139cd5c',
    messagingSenderId: '168191455701',
    projectId: 'fooddisposerapp',
    authDomain: 'fooddisposerapp.firebaseapp.com',
    databaseURL:
        'https://fooddisposerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddisposerapp.firebasestorage.app',
    measurementId: 'G-DNFESZHXZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0_jPBdMMn7FYOwDptg4YhhVENJfDGTk',
    appId: '1:168191455701:android:6eea639fc7fb791a39cd5c',
    messagingSenderId: '168191455701',
    projectId: 'fooddisposerapp',
    databaseURL:
        'https://fooddisposerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddisposerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAz6NxqHv_7V496xjtF5Ng-szVAgWf03Q',
    appId: '1:168191455701:ios:46291fc837d6f60239cd5c',
    messagingSenderId: '168191455701',
    projectId: 'fooddisposerapp',
    databaseURL:
        'https://fooddisposerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddisposerapp.firebasestorage.app',
    iosBundleId: 'com.example.foodDisposerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAz6NxqHv_7V496xjtF5Ng-szVAgWf03Q',
    appId: '1:168191455701:ios:46291fc837d6f60239cd5c',
    messagingSenderId: '168191455701',
    projectId: 'fooddisposerapp',
    databaseURL:
        'https://fooddisposerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddisposerapp.firebasestorage.app',
    iosBundleId: 'com.example.foodDisposerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Tf4QFd5ZOgZ_6kxqsA888gxyuCK3ch8',
    appId: '1:168191455701:web:11d389dcad9e1f8639cd5c',
    messagingSenderId: '168191455701',
    projectId: 'fooddisposerapp',
    authDomain: 'fooddisposerapp.firebaseapp.com',
    databaseURL:
        'https://fooddisposerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddisposerapp.firebasestorage.app',
    measurementId: 'G-KFJ5EYL738',
  );
}
